name: Master Push
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/uchiru/mock-oidc-user-server:v1.0
          cache-from: type=gha
          cache-to: type=gha,mode=max
